--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/GabBiswajit/ReportsDiscord
build-by-default: true
branches:
- main
projects:
  ReportsDiscord:
    path: ""
    lint: false
    libs:
      - src: CortexPE/DiscordWebhookAPI/DiscordWebhookAPI
        version: ^1.0.3
        branch: PM5
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
...
